baseurl: "/StUF-ZTC"
apiname: "StUF-ZTC"
versie-nr: "3.10"
restAPI-Alternatief: "Nee"
url: "http://localhost:4000"

# nav is t.b.v. generatie side-navigation menu.
# Een 'title' zonder path of url genereert slechts een kopje.
# 'path' vormt tezamen met de baseurl de url waarmee de 'href' wordt gevuld. 
# Indien een 'url' voorradig dan wordt daarmee de 'href' gevuld en dient het path slechts om te bepalen welke link active is.
# 'target: blank' zorgt er voor dat de link in een nieuw tabblad wordt geöpend.
nav:
  - title: StUF-ZTC
    subnav:
      - title: Overzicht
        path: /
      - title: StUF-ZTC 3.10
        path: /StUF-ZTC-310
      - title: Documentatie  
        path: /Documentatie
#      - title: Werkgroep  
#        path: /Werkgroep 

plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

remote_theme: VNG-Realisatie/jekyll-theme-vng-realisatie

github: VNG-Realisatie/StUF-ZTC

theme: jekyll-theme-time-machine

project_name: VNG-Realisatie/StUF-ZTC

standard_family: StUF
